language: node_js
node_js:
  - stable
sudo: false
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov |
    ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 06d0......baf0
    secure: Fcs+2yhHHczr7uGs6mw+cKUbG01sHH/S/GVUs7zJfS51Wy07q8mC1VIIFga7aWweAYzPe2yL97VCaYNITmvgES2A/vYc7YTrXJ9Wv0BWZ3DiMgxavK+GyXeNsoSYpRT5Mw+XOnAbg+y1HafHUj1w6gSgGFL97rxVGJPv0S8L8NjfShs7A8b4ZFfN8dxmbkL89qdrCstVETXMiy51+G2xsYEyGDU00k5JyIrOs9YoO5LurHgVdH24lElTW5rVhA4/96zEq+2wTlq3DMhToa0w0L1PoaubdWyG/TMBkvy7qbegGxO1DXxkkNViX3jYubQv1nD5qqyrCI09N+5lXEFDUPT5clqJpZmiKEZhyfZUxFlOARnDj/O+uzjAyks51UYficRL5KT6UzNLzjzVuRPFLVyLk9vLcGc1j99LSBC84J74mTN7Q1B9LA4V5LTcxKJE3SMYAH23PM7SQUz1B2u+y39rG4i501kkzFV4dWXfP9T/z0CSJR84xCGnTlNBdFgIan0mgID3oCmgKaGA0y569Y+X4PPCEzu131Nod/E3txknUwE/SFI3DNUVGHdArOwXsrJOs3tlInz30LNEFGmIrLVgHWsrRpByaq+7BuxqctVwiLaKkC3I67N1DdclZupaMRv2jyV3wr47l2drXAz4+FCl2X9op/m0sNVD/FwmVqs=
  on:
    tags: true
    branch: master
